# Generated by Django 4.2 on 2023-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(to='main.book')),
            ],
        ),
    ]
