# Generated by Django 4.2 on 2023-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='books',
        ),
        migrations.AddField(
            model_name='translation',
            name='book_id',
            field=models.ManyToManyField(related_name='translations', to='main.book'),
        ),
    ]
