# Generated by Django 4.2 on 2023-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='timesTranslated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
