# Generated by Django 4.2 on 2023-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_translation_timestranslated_alter_book_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='timesTranslated',
            field=models.IntegerField(default=1),
        ),
    ]
