# Generated by Django 4.2 on 2023-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_translation_timestranslated'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='normalisation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='definition',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
