# Generated by Django 4.2 on 2023-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_normalisation_alter_translation_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='normalisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
