# Generated by Django 4.2 on 2023-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_chapter_book_alter_page_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='page',
        ),
        migrations.AddField(
            model_name='chapter',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
