# Generated by Django 4.2 on 2023-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='lemma_vals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
