# Generated by Django 4.2 on 2023-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_translation_lemma_vals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='lemma_vals',
            field=models.TextField(null=True),
        ),
    ]
