# Generated by Django 4.2 on 2023-06-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_translation_lemma_vals'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_chapter',
            field=models.IntegerField(null=True),
        ),
    ]
